version: "1.0"

services:
  action:
    image: final
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${PORT}:8080
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:8080", "app:app"]